<?xml version="1.0" encoding="utf-8"?><Database Name="SOFTPETI" Class="DataClasses3DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=SOFTPETI;Integrated Security=True;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="WindowsFormsApp2.Properties.Settings" SettingsPropertyName="SOFTPETIConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.USUARIO" Member="USUARIO">
    <Type Name="USUARIO">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="password_hash" Type="System.String" DbType="VarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="USUARIO_Empresa" Member="Empresa" ThisKey="id" OtherKey="usuario_id" Type="Empresa" />
    </Type>
  </Table>
  <Table Name="dbo.Empresa" Member="Empresa">
    <Type Name="Empresa">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="usuario_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Empresa_Mision" Member="Mision" ThisKey="id" OtherKey="empresa_id" Type="Mision" />
      <Association Name="Empresa_Vision" Member="Vision" ThisKey="id" OtherKey="empresa_id" Type="Vision" />
      <Association Name="Empresa_Valores" Member="Valores" ThisKey="id" OtherKey="empresa_id" Type="Valores" />
      <Association Name="Empresa_ObjetivoG" Member="ObjetivoG" ThisKey="id" OtherKey="empresa_id" Type="ObjetivoG" />
      <Association Name="USUARIO_Empresa" Member="USUARIO" ThisKey="usuario_id" OtherKey="id" Type="USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Mision" Member="Mision">
    <Type Name="Mision">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empresa_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Empresa_Mision" Member="Empresa" ThisKey="empresa_id" OtherKey="id" Type="Empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vision" Member="Vision">
    <Type Name="Vision">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empresa_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Empresa_Vision" Member="Empresa" ThisKey="empresa_id" OtherKey="id" Type="Empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Valores" Member="Valores">
    <Type Name="Valores">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empresa_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Empresa_Valores" Member="Empresa" ThisKey="empresa_id" OtherKey="id" Type="Empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObjetivoG" Member="ObjetivoG">
    <Type Name="ObjetivoG">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empresa_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ObjetivoG_ObjetivoE" Member="ObjetivoE" ThisKey="id" OtherKey="objetivo_id" Type="ObjetivoE" />
      <Association Name="Empresa_ObjetivoG" Member="Empresa" ThisKey="empresa_id" OtherKey="id" Type="Empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ObjetivoE" Member="ObjetivoE">
    <Type Name="ObjetivoE">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="objetivo_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ObjetivoG_ObjetivoE" Member="ObjetivoG" ThisKey="objetivo_id" OtherKey="id" Type="ObjetivoG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MatrizCAME" Member="MatrizCAME">
    <Type Name="MatrizCAME">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo_accion" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="empresa_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.SP_Autenticar" Method="SP_Autenticar">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PasswordHash" Parameter="passwordHash" Type="System.String" DbType="VarChar(64)" />
    <ElementType Name="SP_AutenticarResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarEmpresasPorUsuario" Method="SP_ListarEmpresasPorUsuario">
    <Parameter Name="usuario_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarEmpresasPorUsuarioResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_RegistrarValores" Method="SP_RegistrarValores">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarValores" Method="SP_ListarValores">
    <Parameter Name="EmpresaId" Parameter="empresaId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarValoresResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empresa_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_RegistrarEmpresa" Method="SP_RegistrarEmpresa">
    <Parameter Name="nombre" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="usuario_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="nuevaEmpresaId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarMisionPorUsuario" Method="SP_ListarMisionPorUsuario">
    <Parameter Name="EmpresaId" Parameter="empresaId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarMisionPorUsuarioResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empresa_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_RegistrarMision" Method="SP_RegistrarMision">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_RegistrarVision" Method="SP_RegistrarVision">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarVisionPorUsuario" Method="SP_ListarVisionPorUsuario">
    <Parameter Name="EmpresaId" Parameter="empresaId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarVisionPorUsuarioResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fecha_registro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="empresa_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_RegistrarUnidEstra" Method="SP_RegistrarUnidEstra">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_RegistrarObjetivos" Method="SP_RegistrarObjetivos">
    <Parameter Name="descripcionG1" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="descripcionG2" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="descripcionG3" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="descripcionE1" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="descripcionE2" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="descripcionE3" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="descripcionE4" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="descripcionE5" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="descripcionE6" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarUnidEstraPorEmpresa" Method="SP_ListarUnidEstraPorEmpresa">
    <Parameter Name="EmpresaId" Parameter="empresaId" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarUnidEstraPorEmpresaResult">
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarObjetivosEspecificos" Method="SP_ListarObjetivosEspecificos">
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarObjetivosEspecificosResult">
      <Column Name="ObjetivoE_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ObjetivoE_Descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ObjetivoG_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarObjetivosGenerales" Method="SP_ListarObjetivosGenerales">
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarObjetivosGeneralesResult">
      <Column Name="ObjetivoG_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ObjetivoG_Descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_RegistrarFortaleza" Method="SP_RegistrarFortaleza">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_RegistrarDebilidad" Method="SP_RegistrarDebilidad">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarFortalezas" Method="SP_ListarFortalezas">
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarFortalezasResult">
      <Column Name="Fortaleza_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fortaleza_Descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarDebilidades" Method="SP_ListarDebilidades">
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarDebilidadesResult">
      <Column Name="Debilidad_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Debilidad_Descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_RegistrarOportunidad" Method="SP_RegistrarOportunidad">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_RegistrarAmenaza" Method="SP_RegistrarAmenaza">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarOportunidades" Method="SP_ListarOportunidades">
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarOportunidadesResult">
      <Column Name="Oportunidad_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Oportunidad_Descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarAmenazas" Method="SP_ListarAmenazas">
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarAmenazasResult">
      <Column Name="Amenaza_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amenaza_Descripcion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ListarMatrizCAME" Method="SP_ListarMatrizCAME">
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarMatrizCAMEResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codigo_accion" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="empresa_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_RegistrarMatrizCAME" Method="SP_RegistrarMatrizCAME">
    <Parameter Name="codigo_accion" Type="System.String" DbType="Char(2)" />
    <Parameter Name="descripcion" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="nuevaMatrizCAMEId" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_RegistrarMatrizCAME2" Method="SP_RegistrarMatrizCAME2">
    <Parameter Name="descripcion" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ListarCAME2" Method="SP_ListarCAME2">
    <Parameter Name="empresa_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_ListarCAME2Result">
      <Column Name="CAME_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CAME_Descripcion" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>