#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.Modelos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SOFTPETI")]
	public partial class DataClasses3DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    partial void InsertEmpresa(Empresa instance);
    partial void UpdateEmpresa(Empresa instance);
    partial void DeleteEmpresa(Empresa instance);
    partial void InsertMision(Mision instance);
    partial void UpdateMision(Mision instance);
    partial void DeleteMision(Mision instance);
    partial void InsertVision(Vision instance);
    partial void UpdateVision(Vision instance);
    partial void DeleteVision(Vision instance);
    partial void InsertValores(Valores instance);
    partial void UpdateValores(Valores instance);
    partial void DeleteValores(Valores instance);
    partial void InsertObjetivoG(ObjetivoG instance);
    partial void UpdateObjetivoG(ObjetivoG instance);
    partial void DeleteObjetivoG(ObjetivoG instance);
    partial void InsertObjetivoE(ObjetivoE instance);
    partial void UpdateObjetivoE(ObjetivoE instance);
    partial void DeleteObjetivoE(ObjetivoE instance);
    partial void InsertMatrizCAME(MatrizCAME instance);
    partial void UpdateMatrizCAME(MatrizCAME instance);
    partial void DeleteMatrizCAME(MatrizCAME instance);
    #endregion
		
		public DataClasses3DataContext() : 
				base(global::WindowsFormsApp2.Properties.Settings.Default.SOFTPETIConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIO
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<Empresa> Empresa
		{
			get
			{
				return this.GetTable<Empresa>();
			}
		}
		
		public System.Data.Linq.Table<Mision> Mision
		{
			get
			{
				return this.GetTable<Mision>();
			}
		}
		
		public System.Data.Linq.Table<Vision> Vision
		{
			get
			{
				return this.GetTable<Vision>();
			}
		}
		
		public System.Data.Linq.Table<Valores> Valores
		{
			get
			{
				return this.GetTable<Valores>();
			}
		}
		
		public System.Data.Linq.Table<ObjetivoG> ObjetivoG
		{
			get
			{
				return this.GetTable<ObjetivoG>();
			}
		}
		
		public System.Data.Linq.Table<ObjetivoE> ObjetivoE
		{
			get
			{
				return this.GetTable<ObjetivoE>();
			}
		}
		
		public System.Data.Linq.Table<MatrizCAME> MatrizCAME
		{
			get
			{
				return this.GetTable<MatrizCAME>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Autenticar")]
		public ISingleResult<SP_AutenticarResult> SP_Autenticar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PasswordHash", DbType="VarChar(64)")] string passwordHash)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, passwordHash);
			return ((ISingleResult<SP_AutenticarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarEmpresasPorUsuario")]
		public ISingleResult<SP_ListarEmpresasPorUsuarioResult> SP_ListarEmpresasPorUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> usuario_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario_id);
			return ((ISingleResult<SP_ListarEmpresasPorUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarValores")]
		public int SP_RegistrarValores([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, empresa_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarValores")]
		public ISingleResult<SP_ListarValoresResult> SP_ListarValores([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpresaId", DbType="Int")] System.Nullable<int> empresaId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresaId);
			return ((ISingleResult<SP_ListarValoresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarEmpresa")]
		public int SP_RegistrarEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> usuario_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> nuevaEmpresaId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, usuario_id, descripcion, nuevaEmpresaId);
			nuevaEmpresaId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarMisionPorUsuario")]
		public ISingleResult<SP_ListarMisionPorUsuarioResult> SP_ListarMisionPorUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpresaId", DbType="Int")] System.Nullable<int> empresaId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresaId);
			return ((ISingleResult<SP_ListarMisionPorUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarMision")]
		public int SP_RegistrarMision([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, empresa_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarVision")]
		public int SP_RegistrarVision([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, empresa_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarVisionPorUsuario")]
		public ISingleResult<SP_ListarVisionPorUsuarioResult> SP_ListarVisionPorUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpresaId", DbType="Int")] System.Nullable<int> empresaId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresaId);
			return ((ISingleResult<SP_ListarVisionPorUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarUnidEstra")]
		public int SP_RegistrarUnidEstra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, empresa_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarObjetivos")]
		public int SP_RegistrarObjetivos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcionG1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcionG2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcionG3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcionE1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcionE2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcionE3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcionE4, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcionE5, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcionE6)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcionG1, descripcionG2, descripcionG3, empresa_id, descripcionE1, descripcionE2, descripcionE3, descripcionE4, descripcionE5, descripcionE6);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarUnidEstraPorEmpresa")]
		public ISingleResult<SP_ListarUnidEstraPorEmpresaResult> SP_ListarUnidEstraPorEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpresaId", DbType="Int")] System.Nullable<int> empresaId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresaId);
			return ((ISingleResult<SP_ListarUnidEstraPorEmpresaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarObjetivosEspecificos")]
		public ISingleResult<SP_ListarObjetivosEspecificosResult> SP_ListarObjetivosEspecificos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresa_id);
			return ((ISingleResult<SP_ListarObjetivosEspecificosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarObjetivosGenerales")]
		public ISingleResult<SP_ListarObjetivosGeneralesResult> SP_ListarObjetivosGenerales([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresa_id);
			return ((ISingleResult<SP_ListarObjetivosGeneralesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarFortaleza")]
		public int SP_RegistrarFortaleza([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, empresa_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarDebilidad")]
		public int SP_RegistrarDebilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, empresa_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarFortalezas")]
		public ISingleResult<SP_ListarFortalezasResult> SP_ListarFortalezas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresa_id);
			return ((ISingleResult<SP_ListarFortalezasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarDebilidades")]
		public ISingleResult<SP_ListarDebilidadesResult> SP_ListarDebilidades([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresa_id);
			return ((ISingleResult<SP_ListarDebilidadesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarOportunidad")]
		public int SP_RegistrarOportunidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, empresa_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarAmenaza")]
		public int SP_RegistrarAmenaza([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, empresa_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarOportunidades")]
		public ISingleResult<SP_ListarOportunidadesResult> SP_ListarOportunidades([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresa_id);
			return ((ISingleResult<SP_ListarOportunidadesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarAmenazas")]
		public ISingleResult<SP_ListarAmenazasResult> SP_ListarAmenazas([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresa_id);
			return ((ISingleResult<SP_ListarAmenazasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarMatrizCAME")]
		public ISingleResult<SP_ListarMatrizCAMEResult> SP_ListarMatrizCAME([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresa_id);
			return ((ISingleResult<SP_ListarMatrizCAMEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarMatrizCAME")]
		public int SP_RegistrarMatrizCAME([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string codigo_accion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> nuevaMatrizCAMEId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo_accion, descripcion, empresa_id, nuevaMatrizCAMEId);
			nuevaMatrizCAMEId = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RegistrarMatrizCAME2")]
		public int SP_RegistrarMatrizCAME2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, empresa_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarCAME2")]
		public ISingleResult<SP_ListarCAME2Result> SP_ListarCAME2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> empresa_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empresa_id);
			return ((ISingleResult<SP_ListarCAME2Result>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIO")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _email;
		
		private string _password_hash;
		
		private EntitySet<Empresa> _Empresa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onpassword_hashChanging(string value);
    partial void Onpassword_hashChanged();
    #endregion
		
		public USUARIO()
		{
			this._Empresa = new EntitySet<Empresa>(new Action<Empresa>(this.attach_Empresa), new Action<Empresa>(this.detach_Empresa));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(120) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password_hash", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string password_hash
		{
			get
			{
				return this._password_hash;
			}
			set
			{
				if ((this._password_hash != value))
				{
					this.Onpassword_hashChanging(value);
					this.SendPropertyChanging();
					this._password_hash = value;
					this.SendPropertyChanged("password_hash");
					this.Onpassword_hashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_Empresa", Storage="_Empresa", ThisKey="id", OtherKey="usuario_id")]
		public EntitySet<Empresa> Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				this._Empresa.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empresa(Empresa entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO = this;
		}
		
		private void detach_Empresa(Empresa entity)
		{
			this.SendPropertyChanging();
			entity.USUARIO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empresa")]
	public partial class Empresa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private System.Nullable<int> _usuario_id;
		
		private string _descripcion;
		
		private EntitySet<Mision> _Mision;
		
		private EntitySet<Vision> _Vision;
		
		private EntitySet<Valores> _Valores;
		
		private EntitySet<ObjetivoG> _ObjetivoG;
		
		private EntityRef<USUARIO> _USUARIO;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onusuario_idChanging(System.Nullable<int> value);
    partial void Onusuario_idChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Empresa()
		{
			this._Mision = new EntitySet<Mision>(new Action<Mision>(this.attach_Mision), new Action<Mision>(this.detach_Mision));
			this._Vision = new EntitySet<Vision>(new Action<Vision>(this.attach_Vision), new Action<Vision>(this.detach_Vision));
			this._Valores = new EntitySet<Valores>(new Action<Valores>(this.attach_Valores), new Action<Valores>(this.detach_Valores));
			this._ObjetivoG = new EntitySet<ObjetivoG>(new Action<ObjetivoG>(this.attach_ObjetivoG), new Action<ObjetivoG>(this.detach_ObjetivoG));
			this._USUARIO = default(EntityRef<USUARIO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(200)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario_id", DbType="Int")]
		public System.Nullable<int> usuario_id
		{
			get
			{
				return this._usuario_id;
			}
			set
			{
				if ((this._usuario_id != value))
				{
					if (this._USUARIO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusuario_idChanging(value);
					this.SendPropertyChanging();
					this._usuario_id = value;
					this.SendPropertyChanged("usuario_id");
					this.Onusuario_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresa_Mision", Storage="_Mision", ThisKey="id", OtherKey="empresa_id")]
		public EntitySet<Mision> Mision
		{
			get
			{
				return this._Mision;
			}
			set
			{
				this._Mision.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresa_Vision", Storage="_Vision", ThisKey="id", OtherKey="empresa_id")]
		public EntitySet<Vision> Vision
		{
			get
			{
				return this._Vision;
			}
			set
			{
				this._Vision.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresa_Valores", Storage="_Valores", ThisKey="id", OtherKey="empresa_id")]
		public EntitySet<Valores> Valores
		{
			get
			{
				return this._Valores;
			}
			set
			{
				this._Valores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresa_ObjetivoG", Storage="_ObjetivoG", ThisKey="id", OtherKey="empresa_id")]
		public EntitySet<ObjetivoG> ObjetivoG
		{
			get
			{
				return this._ObjetivoG;
			}
			set
			{
				this._ObjetivoG.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIO_Empresa", Storage="_USUARIO", ThisKey="usuario_id", OtherKey="id", IsForeignKey=true)]
		public USUARIO USUARIO
		{
			get
			{
				return this._USUARIO.Entity;
			}
			set
			{
				USUARIO previousValue = this._USUARIO.Entity;
				if (((previousValue != value) 
							|| (this._USUARIO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USUARIO.Entity = null;
						previousValue.Empresa.Remove(this);
					}
					this._USUARIO.Entity = value;
					if ((value != null))
					{
						value.Empresa.Add(this);
						this._usuario_id = value.id;
					}
					else
					{
						this._usuario_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("USUARIO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Mision(Mision entity)
		{
			this.SendPropertyChanging();
			entity.Empresa = this;
		}
		
		private void detach_Mision(Mision entity)
		{
			this.SendPropertyChanging();
			entity.Empresa = null;
		}
		
		private void attach_Vision(Vision entity)
		{
			this.SendPropertyChanging();
			entity.Empresa = this;
		}
		
		private void detach_Vision(Vision entity)
		{
			this.SendPropertyChanging();
			entity.Empresa = null;
		}
		
		private void attach_Valores(Valores entity)
		{
			this.SendPropertyChanging();
			entity.Empresa = this;
		}
		
		private void detach_Valores(Valores entity)
		{
			this.SendPropertyChanging();
			entity.Empresa = null;
		}
		
		private void attach_ObjetivoG(ObjetivoG entity)
		{
			this.SendPropertyChanging();
			entity.Empresa = this;
		}
		
		private void detach_ObjetivoG(ObjetivoG entity)
		{
			this.SendPropertyChanging();
			entity.Empresa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mision")]
	public partial class Mision : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private System.Nullable<int> _empresa_id;
		
		private EntityRef<Empresa> _Empresa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_registroChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_registroChanged();
    partial void Onempresa_idChanging(System.Nullable<int> value);
    partial void Onempresa_idChanged();
    #endregion
		
		public Mision()
		{
			this._Empresa = default(EntityRef<Empresa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empresa_id", DbType="Int")]
		public System.Nullable<int> empresa_id
		{
			get
			{
				return this._empresa_id;
			}
			set
			{
				if ((this._empresa_id != value))
				{
					if (this._Empresa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onempresa_idChanging(value);
					this.SendPropertyChanging();
					this._empresa_id = value;
					this.SendPropertyChanged("empresa_id");
					this.Onempresa_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresa_Mision", Storage="_Empresa", ThisKey="empresa_id", OtherKey="id", IsForeignKey=true)]
		public Empresa Empresa
		{
			get
			{
				return this._Empresa.Entity;
			}
			set
			{
				Empresa previousValue = this._Empresa.Entity;
				if (((previousValue != value) 
							|| (this._Empresa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empresa.Entity = null;
						previousValue.Mision.Remove(this);
					}
					this._Empresa.Entity = value;
					if ((value != null))
					{
						value.Mision.Add(this);
						this._empresa_id = value.id;
					}
					else
					{
						this._empresa_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Empresa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vision")]
	public partial class Vision : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private System.Nullable<int> _empresa_id;
		
		private EntityRef<Empresa> _Empresa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_registroChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_registroChanged();
    partial void Onempresa_idChanging(System.Nullable<int> value);
    partial void Onempresa_idChanged();
    #endregion
		
		public Vision()
		{
			this._Empresa = default(EntityRef<Empresa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empresa_id", DbType="Int")]
		public System.Nullable<int> empresa_id
		{
			get
			{
				return this._empresa_id;
			}
			set
			{
				if ((this._empresa_id != value))
				{
					if (this._Empresa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onempresa_idChanging(value);
					this.SendPropertyChanging();
					this._empresa_id = value;
					this.SendPropertyChanged("empresa_id");
					this.Onempresa_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresa_Vision", Storage="_Empresa", ThisKey="empresa_id", OtherKey="id", IsForeignKey=true)]
		public Empresa Empresa
		{
			get
			{
				return this._Empresa.Entity;
			}
			set
			{
				Empresa previousValue = this._Empresa.Entity;
				if (((previousValue != value) 
							|| (this._Empresa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empresa.Entity = null;
						previousValue.Vision.Remove(this);
					}
					this._Empresa.Entity = value;
					if ((value != null))
					{
						value.Vision.Add(this);
						this._empresa_id = value.id;
					}
					else
					{
						this._empresa_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Empresa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Valores")]
	public partial class Valores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private System.Nullable<int> _empresa_id;
		
		private EntityRef<Empresa> _Empresa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_registroChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_registroChanged();
    partial void Onempresa_idChanging(System.Nullable<int> value);
    partial void Onempresa_idChanged();
    #endregion
		
		public Valores()
		{
			this._Empresa = default(EntityRef<Empresa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empresa_id", DbType="Int")]
		public System.Nullable<int> empresa_id
		{
			get
			{
				return this._empresa_id;
			}
			set
			{
				if ((this._empresa_id != value))
				{
					if (this._Empresa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onempresa_idChanging(value);
					this.SendPropertyChanging();
					this._empresa_id = value;
					this.SendPropertyChanged("empresa_id");
					this.Onempresa_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresa_Valores", Storage="_Empresa", ThisKey="empresa_id", OtherKey="id", IsForeignKey=true)]
		public Empresa Empresa
		{
			get
			{
				return this._Empresa.Entity;
			}
			set
			{
				Empresa previousValue = this._Empresa.Entity;
				if (((previousValue != value) 
							|| (this._Empresa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empresa.Entity = null;
						previousValue.Valores.Remove(this);
					}
					this._Empresa.Entity = value;
					if ((value != null))
					{
						value.Valores.Add(this);
						this._empresa_id = value.id;
					}
					else
					{
						this._empresa_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Empresa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObjetivoG")]
	public partial class ObjetivoG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private System.Nullable<int> _empresa_id;
		
		private EntitySet<ObjetivoE> _ObjetivoE;
		
		private EntityRef<Empresa> _Empresa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_registroChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_registroChanged();
    partial void Onempresa_idChanging(System.Nullable<int> value);
    partial void Onempresa_idChanged();
    #endregion
		
		public ObjetivoG()
		{
			this._ObjetivoE = new EntitySet<ObjetivoE>(new Action<ObjetivoE>(this.attach_ObjetivoE), new Action<ObjetivoE>(this.detach_ObjetivoE));
			this._Empresa = default(EntityRef<Empresa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empresa_id", DbType="Int")]
		public System.Nullable<int> empresa_id
		{
			get
			{
				return this._empresa_id;
			}
			set
			{
				if ((this._empresa_id != value))
				{
					if (this._Empresa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onempresa_idChanging(value);
					this.SendPropertyChanging();
					this._empresa_id = value;
					this.SendPropertyChanged("empresa_id");
					this.Onempresa_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ObjetivoG_ObjetivoE", Storage="_ObjetivoE", ThisKey="id", OtherKey="objetivo_id")]
		public EntitySet<ObjetivoE> ObjetivoE
		{
			get
			{
				return this._ObjetivoE;
			}
			set
			{
				this._ObjetivoE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresa_ObjetivoG", Storage="_Empresa", ThisKey="empresa_id", OtherKey="id", IsForeignKey=true)]
		public Empresa Empresa
		{
			get
			{
				return this._Empresa.Entity;
			}
			set
			{
				Empresa previousValue = this._Empresa.Entity;
				if (((previousValue != value) 
							|| (this._Empresa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empresa.Entity = null;
						previousValue.ObjetivoG.Remove(this);
					}
					this._Empresa.Entity = value;
					if ((value != null))
					{
						value.ObjetivoG.Add(this);
						this._empresa_id = value.id;
					}
					else
					{
						this._empresa_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Empresa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ObjetivoE(ObjetivoE entity)
		{
			this.SendPropertyChanging();
			entity.ObjetivoG = this;
		}
		
		private void detach_ObjetivoE(ObjetivoE entity)
		{
			this.SendPropertyChanging();
			entity.ObjetivoG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ObjetivoE")]
	public partial class ObjetivoE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private System.Nullable<int> _objetivo_id;
		
		private EntityRef<ObjetivoG> _ObjetivoG;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_registroChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_registroChanged();
    partial void Onobjetivo_idChanging(System.Nullable<int> value);
    partial void Onobjetivo_idChanged();
    #endregion
		
		public ObjetivoE()
		{
			this._ObjetivoG = default(EntityRef<ObjetivoG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this.Onfecha_registroChanging(value);
					this.SendPropertyChanging();
					this._fecha_registro = value;
					this.SendPropertyChanged("fecha_registro");
					this.Onfecha_registroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objetivo_id", DbType="Int")]
		public System.Nullable<int> objetivo_id
		{
			get
			{
				return this._objetivo_id;
			}
			set
			{
				if ((this._objetivo_id != value))
				{
					if (this._ObjetivoG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onobjetivo_idChanging(value);
					this.SendPropertyChanging();
					this._objetivo_id = value;
					this.SendPropertyChanged("objetivo_id");
					this.Onobjetivo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ObjetivoG_ObjetivoE", Storage="_ObjetivoG", ThisKey="objetivo_id", OtherKey="id", IsForeignKey=true)]
		public ObjetivoG ObjetivoG
		{
			get
			{
				return this._ObjetivoG.Entity;
			}
			set
			{
				ObjetivoG previousValue = this._ObjetivoG.Entity;
				if (((previousValue != value) 
							|| (this._ObjetivoG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ObjetivoG.Entity = null;
						previousValue.ObjetivoE.Remove(this);
					}
					this._ObjetivoG.Entity = value;
					if ((value != null))
					{
						value.ObjetivoE.Add(this);
						this._objetivo_id = value.id;
					}
					else
					{
						this._objetivo_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("ObjetivoG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MatrizCAME")]
	public partial class MatrizCAME : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _codigo_accion;
		
		private string _descripcion;
		
		private int _empresa_id;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncodigo_accionChanging(string value);
    partial void Oncodigo_accionChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onempresa_idChanging(int value);
    partial void Onempresa_idChanged();
    #endregion
		
		public MatrizCAME()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_accion", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string codigo_accion
		{
			get
			{
				return this._codigo_accion;
			}
			set
			{
				if ((this._codigo_accion != value))
				{
					this.Oncodigo_accionChanging(value);
					this.SendPropertyChanging();
					this._codigo_accion = value;
					this.SendPropertyChanged("codigo_accion");
					this.Oncodigo_accionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empresa_id", DbType="Int NOT NULL")]
		public int empresa_id
		{
			get
			{
				return this._empresa_id;
			}
			set
			{
				if ((this._empresa_id != value))
				{
					this.Onempresa_idChanging(value);
					this.SendPropertyChanging();
					this._empresa_id = value;
					this.SendPropertyChanged("empresa_id");
					this.Onempresa_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_AutenticarResult
	{
		
		private int _id;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _email;
		
		public SP_AutenticarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(120) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this._apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
	}
	
	public partial class SP_ListarEmpresasPorUsuarioResult
	{
		
		private int _id;
		
		private string _nombre;
		
		public SP_ListarEmpresasPorUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(200)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
	}
	
	public partial class SP_ListarValoresResult
	{
		
		private int _id;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private System.Nullable<int> _empresa_id;
		
		public SP_ListarValoresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this._fecha_registro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empresa_id", DbType="Int")]
		public System.Nullable<int> empresa_id
		{
			get
			{
				return this._empresa_id;
			}
			set
			{
				if ((this._empresa_id != value))
				{
					this._empresa_id = value;
				}
			}
		}
	}
	
	public partial class SP_ListarMisionPorUsuarioResult
	{
		
		private int _id;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private System.Nullable<int> _empresa_id;
		
		public SP_ListarMisionPorUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this._fecha_registro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empresa_id", DbType="Int")]
		public System.Nullable<int> empresa_id
		{
			get
			{
				return this._empresa_id;
			}
			set
			{
				if ((this._empresa_id != value))
				{
					this._empresa_id = value;
				}
			}
		}
	}
	
	public partial class SP_ListarVisionPorUsuarioResult
	{
		
		private int _id;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_registro;
		
		private System.Nullable<int> _empresa_id;
		
		public SP_ListarVisionPorUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_registro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_registro
		{
			get
			{
				return this._fecha_registro;
			}
			set
			{
				if ((this._fecha_registro != value))
				{
					this._fecha_registro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empresa_id", DbType="Int")]
		public System.Nullable<int> empresa_id
		{
			get
			{
				return this._empresa_id;
			}
			set
			{
				if ((this._empresa_id != value))
				{
					this._empresa_id = value;
				}
			}
		}
	}
	
	public partial class SP_ListarUnidEstraPorEmpresaResult
	{
		
		private string _descripcion;
		
		public SP_ListarUnidEstraPorEmpresaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarObjetivosEspecificosResult
	{
		
		private int _ObjetivoE_Id;
		
		private string _ObjetivoE_Descripcion;
		
		private System.Nullable<int> _ObjetivoG_Id;
		
		public SP_ListarObjetivosEspecificosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjetivoE_Id", DbType="Int NOT NULL")]
		public int ObjetivoE_Id
		{
			get
			{
				return this._ObjetivoE_Id;
			}
			set
			{
				if ((this._ObjetivoE_Id != value))
				{
					this._ObjetivoE_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjetivoE_Descripcion", DbType="NVarChar(MAX)")]
		public string ObjetivoE_Descripcion
		{
			get
			{
				return this._ObjetivoE_Descripcion;
			}
			set
			{
				if ((this._ObjetivoE_Descripcion != value))
				{
					this._ObjetivoE_Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjetivoG_Id", DbType="Int")]
		public System.Nullable<int> ObjetivoG_Id
		{
			get
			{
				return this._ObjetivoG_Id;
			}
			set
			{
				if ((this._ObjetivoG_Id != value))
				{
					this._ObjetivoG_Id = value;
				}
			}
		}
	}
	
	public partial class SP_ListarObjetivosGeneralesResult
	{
		
		private int _ObjetivoG_Id;
		
		private string _ObjetivoG_Descripcion;
		
		public SP_ListarObjetivosGeneralesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjetivoG_Id", DbType="Int NOT NULL")]
		public int ObjetivoG_Id
		{
			get
			{
				return this._ObjetivoG_Id;
			}
			set
			{
				if ((this._ObjetivoG_Id != value))
				{
					this._ObjetivoG_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjetivoG_Descripcion", DbType="NVarChar(MAX)")]
		public string ObjetivoG_Descripcion
		{
			get
			{
				return this._ObjetivoG_Descripcion;
			}
			set
			{
				if ((this._ObjetivoG_Descripcion != value))
				{
					this._ObjetivoG_Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarFortalezasResult
	{
		
		private int _Fortaleza_Id;
		
		private string _Fortaleza_Descripcion;
		
		public SP_ListarFortalezasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fortaleza_Id", DbType="Int NOT NULL")]
		public int Fortaleza_Id
		{
			get
			{
				return this._Fortaleza_Id;
			}
			set
			{
				if ((this._Fortaleza_Id != value))
				{
					this._Fortaleza_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fortaleza_Descripcion", DbType="NVarChar(MAX)")]
		public string Fortaleza_Descripcion
		{
			get
			{
				return this._Fortaleza_Descripcion;
			}
			set
			{
				if ((this._Fortaleza_Descripcion != value))
				{
					this._Fortaleza_Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarDebilidadesResult
	{
		
		private int _Debilidad_Id;
		
		private string _Debilidad_Descripcion;
		
		public SP_ListarDebilidadesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debilidad_Id", DbType="Int NOT NULL")]
		public int Debilidad_Id
		{
			get
			{
				return this._Debilidad_Id;
			}
			set
			{
				if ((this._Debilidad_Id != value))
				{
					this._Debilidad_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Debilidad_Descripcion", DbType="NVarChar(MAX)")]
		public string Debilidad_Descripcion
		{
			get
			{
				return this._Debilidad_Descripcion;
			}
			set
			{
				if ((this._Debilidad_Descripcion != value))
				{
					this._Debilidad_Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarOportunidadesResult
	{
		
		private int _Oportunidad_Id;
		
		private string _Oportunidad_Descripcion;
		
		public SP_ListarOportunidadesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oportunidad_Id", DbType="Int NOT NULL")]
		public int Oportunidad_Id
		{
			get
			{
				return this._Oportunidad_Id;
			}
			set
			{
				if ((this._Oportunidad_Id != value))
				{
					this._Oportunidad_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oportunidad_Descripcion", DbType="NVarChar(MAX)")]
		public string Oportunidad_Descripcion
		{
			get
			{
				return this._Oportunidad_Descripcion;
			}
			set
			{
				if ((this._Oportunidad_Descripcion != value))
				{
					this._Oportunidad_Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarAmenazasResult
	{
		
		private int _Amenaza_Id;
		
		private string _Amenaza_Descripcion;
		
		public SP_ListarAmenazasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amenaza_Id", DbType="Int NOT NULL")]
		public int Amenaza_Id
		{
			get
			{
				return this._Amenaza_Id;
			}
			set
			{
				if ((this._Amenaza_Id != value))
				{
					this._Amenaza_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amenaza_Descripcion", DbType="NVarChar(MAX)")]
		public string Amenaza_Descripcion
		{
			get
			{
				return this._Amenaza_Descripcion;
			}
			set
			{
				if ((this._Amenaza_Descripcion != value))
				{
					this._Amenaza_Descripcion = value;
				}
			}
		}
	}
	
	public partial class SP_ListarMatrizCAMEResult
	{
		
		private int _id;
		
		private string _codigo_accion;
		
		private string _descripcion;
		
		private int _empresa_id;
		
		public SP_ListarMatrizCAMEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_accion", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string codigo_accion
		{
			get
			{
				return this._codigo_accion;
			}
			set
			{
				if ((this._codigo_accion != value))
				{
					this._codigo_accion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empresa_id", DbType="Int NOT NULL")]
		public int empresa_id
		{
			get
			{
				return this._empresa_id;
			}
			set
			{
				if ((this._empresa_id != value))
				{
					this._empresa_id = value;
				}
			}
		}
	}
	
	public partial class SP_ListarCAME2Result
	{
		
		private int _CAME_Id;
		
		private string _CAME_Descripcion;
		
		public SP_ListarCAME2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAME_Id", DbType="Int NOT NULL")]
		public int CAME_Id
		{
			get
			{
				return this._CAME_Id;
			}
			set
			{
				if ((this._CAME_Id != value))
				{
					this._CAME_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAME_Descripcion", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CAME_Descripcion
		{
			get
			{
				return this._CAME_Descripcion;
			}
			set
			{
				if ((this._CAME_Descripcion != value))
				{
					this._CAME_Descripcion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
